### ISSUE TITLE
It's not working for stateless component

### ISSUE THREAD

**Issue by budarin** [maicki/why-did-you-update#10]
I have stateless component and it has rendered every time with state changing, but package doesnt register this.
When I change it to class component - everything works perfect.

**Comment by OliverJAsh** [comment]
> Somewhere after react@15.2.0 the createClass is not called for function components anymore. It means that the original monkey-patch doesn't work. 

https://github.com/garbles/why-did-you-update/issues/46

I'm not sure what we can do about this, but I'd love to see support restored for stateless function components.

**Comment by budarin** [comment]
maybe wrap into HOC ?

**Comment by maicki** [comment]
It's currently in the early stage but in this branch there is a HOC which should work for all kinds of components: https://github.com/maicki/why-did-you-update/tree/MSHOC

If someone has any idea how to wrap a component automatically into a HOC without explicitly wrap it let me know :)

**Comment by OliverJAsh** [comment]
React's dev tools extension has a "Highlight Updates" feature that doesn't seem to suffer from the issue we have here, nor from when components override `componentDidUpdate` (https://github.com/garbles/why-did-you-update/issues/19).

I asked @gaearon on Twitter if he could provide any insight into how this works https://mobile.twitter.com/OliverJAsh/status/957326530128080897. Potentially we could borrow the same mechanism to solve the issues we have.

**Comment by danburzo** [comment]
This pull request that proposes an alternative monkey-patching approach works with functional components as well: https://github.com/maicki/why-did-you-update/pull/20

**Comment by vzaidman** [comment]
fixed by #20
