### ISSUE TITLE
Document default exclude

### ISSUE THREAD

**Issue by OliverJAsh** [maicki/why-did-you-update#11]
I was surprised to find that none of my components created via HOCs were being logged.

This appears to be because the default `exclude` includes only alphanumeric characters: https://github.com/maicki/why-did-you-update/blob/0095d1344bbc92bf6226d6d3bc2709ece243259c/src/normalizeOptions.js#L6

Components created through HOCs often have brackets in them, for example `pure(MyComponent)`.

Can we document the default exclude so this behaviour is less surprising?

**Comment by maicki** [comment]
@OliverJAsh I just pushed to master to add brackets to the default exclude. This should fix this issue. Thanks for bringing it up.

**Comment by OliverJAsh** [comment]
@maicki Would you accept a PR to add a note somewhere in the docs about the `DEFAULT_EXCLUDE`?

**Comment by maicki** [comment]
@OliverJAsh Yes for sure!
