### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by brunolemos** [maicki/why-did-you-update#13]
I don't know what's causing this.
It's an almost empty app using `react-native-navigation` and `react-native-vector-icons`.

BTW it just happens if I use a custom `exclude`.
Currently using `exclude: /^CellRenderer|Icon|Swipeable/`.

![gif](https://user-images.githubusercontent.com/619186/34116434-c982be50-e3ff-11e7-8144-1731f40ffe13.gif)

```json
  "dependencies":  @{
    "gravatar": "^1.6.0",
    "ramda": "^0.25.0",
    "react": "^16.2.0",
    "react-native": "^0.51.0",
    "react-native-gesture-handler": "^1.0.0-alpha.35",
    "react-native-navigation": "^1.1.311",
    "react-native-safari-view": "^2.1.0",
    "react-native-safe-area-view": "^0.2.0",
    "react-native-vector-icons": "^4.4.2",
    "warna": "^0.2.4"
  },
  "devDependencies": {
    "why-did-you-update": "^0.1.0"
  },
```

**Comment by brunolemos** [comment]
I added a `console.trace` on this repo code but it didn't help:

```

  | componentDidUpdate | @ | index.js:33
-- | -- | -- | --
  | commitLifeCycles | @ | ReactNativeFiber-dev.js:2174
  | commitAllLifeCycles | @ | ReactNativeFiber-dev.js:2459
  | _invokeGuardedCallback | @ | ReactNativeFiber-dev.js:73
  | invokeGuardedCallback | @ | ReactNativeFiber-dev.js:47
  | commitAllWork | @ | ReactNativeFiber-dev.js:2485
  | workLoop | @ | ReactNativeFiber-dev.js:2555
  | _invokeGuardedCallback | @ | ReactNativeFiber-dev.js:73
  | invokeGuardedCallback | @ | ReactNativeFiber-dev.js:47
  | performWork | @ | ReactNativeFiber-dev.js:2593
  | scheduleUpdateImpl | @ | ReactNativeFiber-dev.js:2728
  | scheduleUpdate | @ | ReactNativeFiber-dev.js:2711
  | enqueueSetState | @ | ReactNativeFiber-dev.js:1514
  | Component.setState | @ | react.development.js:237
  | (anonymous) | @ | YellowBox.js:363
  | (anonymous) | @ | JSTimers.js:301
  | _callTimer | @ | JSTimers.js:154
  | _callImmediatesPass | @ | JSTimers.js:202
  | callImmediates | @ | JSTimers.js:470
  | __callImmediates | @ | MessageQueue.js:275
  | (anonymous) | @ | MessageQueue.js:140
  | __guard | @ | MessageQueue.js:262
  | flushedQueue | @ | MessageQueue.js:139
  | callFunctionReturnFlushedQueue | @ | MessageQueue.js:114
  | (anonymous) | @ | debuggerWorker.js:72
```

**Comment by brunolemos** [comment]
Changing `exclude:  /^CellRenderer|Icon|Swipeable/` to `exclude:  /[^a-zA-Z0-9]|CellRenderer|Icon|Swipeable/` fixes it but I don't know why it's necessary.

**Comment by jondot** [comment]
This happens because `console.warn` maps to React Native YellowBox. YellowBox is an ordinary component which contains `Text` elements, which `wdyu` has an opinion about, spits out some more `warn`s and there you have it - an infinite loop.
The proper way is to make sure the `console.warn` bit is configurable. I suggest reopening this issue.

**Comment by maicki** [comment]
I just pushed the commit linked above that in RN disable's the yellow box before calling `console.warn`. I don't see a reason yet for providing a RN related notifier besides the default notifier and as @jondot said everyone could provide a different one if necessary.

That said in the future I could see to provide a better abstraction around the notifiers so it's easier to hook into it.

@brunolemos Please let me know if latest master resolves does not resolve this issue and reopen. Thanks!.

**Comment by rodrigobdz** [comment]
@maicki I'm having the exact same issue as @brunolemos.

>   React Native Environment Info:
>     System:
>       OS: macOS High Sierra 10.13.6
>       CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
>       Memory: 46.20 MB / 16.00 GB
>       Shell: 2.7.1 - /usr/local/bin/fish
>     Binaries:
>       Node: 8.11.3 - /usr/local/opt/node@8/bin/node
>       Yarn: 1.7.0 - /usr/local/bin/yarn
>       npm: 5.6.0 - /usr/local/opt/node@8/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
>       Android SDK:
>         Build Tools: 23.0.1, 26.0.1, 26.0.3
>         API Levels: 23, 26
>     IDEs:
>       Android Studio: 3.1 AI-173.4819257
>       Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
>     npmPackages:
>       react: ^16.4.1 => 16.4.1
>       react-native: ^0.56.0 => 0.56.0
>     npmGlobalPackages:
>       create-react-native-app: 1.0.0
>       react-native-cli: 2.0.1
>       react-native-git-upgrade: 0.2.7

**Comment by maicki** [comment]
@rodrigobdz Hey - would it be possible to provide some sample project and what version are you using of `why-did-you-update`?

**Comment by rodrigobdz** [comment]
I'm using version `0.1.1`. Unfortunately, I'm not able to provide a sample project at the moment :(

**Comment by alvelig** [comment]
I had to modify `defaultNotifier.js`:
```
25 var consoleWarn = function consoleWarn(args) {
26 -  var oldDisableYellowBox = console.disableYellowBox;
27 -   console.disableYellowBox = true;
28 -   console.warn(args);
29 +  console.log(args);
30 -   console.disableYellowBox = oldDisableYellowBox;
31 };
```
