### ISSUE TITLE
Add context into verification process

### ISSUE THREAD

**Issue by budarin** [maicki/why-did-you-update#14]
I've use to analogue of react-router where route information is passed through the React's context and every page transition I see in console warnings from those components, though their context has changed
 
![default](https://user-images.githubusercontent.com/8055157/34641509-a0b7f8c0-f316-11e7-88f7-4fac257f1ccd.png)

**Comment by maicki** [comment]
Hey @budarin, there is no current plan to add context into the diff algorithm. I would suggest you exclude this components via the `exclude` option you pass into the `whyDidYouUpdate` function as second parameter. Thanks!

**Comment by johnunclesam** [comment]
@maicki I'm wrong if I say that "`react-router`" should be excluded from `why-did-you-update`?

I'm using the latest version, but it's still a mess...
