### ISSUE TITLE
Script to export logs to CSV

### ISSUE THREAD

**Issue by kelset** [maicki/why-did-you-update#15]
Hey 👋
Thanks for maintaining this fork of the lib, it's prob one of the few ones that still works for performance benchmarking in React Native (JS side) 😅

Since what `why-did-you-update` do is printing to console, to easily get an idea of what's wasting time I created [this script](https://gist.github.com/kelset/9e785cab59c48312b658cbb05eb631c0) to parse and convert a saved log to a CSV, so that then I can easily import into GSheet to analyse/keep track.

I have no idea how/if there is a way to integrate it / add it as a feature for the lib itself, but if you want I can do a PR to the README to add a reference to it.

**Comment by maicki** [comment]
@kelset Hey, I would appreciate a PR to the README! Just a heads the output of function only changes will change though. Thanks!

**Comment by kelset** [comment]
> the output of function only changes will change

I'm not sure I've understood what you mean there 😅

**Comment by maicki** [comment]
@kelset Never mind, reading again over it doesn't really makes sense :) Also looking over your script, the change we will make in the output will not effect your script anyway so we should be good.

**Comment by vzaidman** [comment]
@kelset did you try using the `notifier` option to write to a more convenient place? maybe some kind of separate file?

**Comment by vzaidman** [comment]
OK!
You are welcome to reopen if you have anymore questions.
