### ISSUE TITLE
Aggregate all errors

### ISSUE THREAD

**Issue by OliverJAsh** [maicki/why-did-you-update#18]
If components update for multiple reasons (e.g. new objects *and* new functions), we only log one of those reasons. Ideally all reasons would be displayed at once to make the debugging experience easier.

E.g., if we render this twice:

``` jsx
// (ClassDemo is not a PureComponent)
<ClassDemo a={1} b={{c: {d: 4}}} e={function something () {}} f={1} />
```

There are multiple avoidable reasons why `ClassDemo` will update:

- Functions for props `e` are not reference equal but are similar.
- Objects for props `b` are not reference equal but are deep equal.
- Props `a` and `f` are reference equal, but component is not `PureComponent`.

Currently we only log:

```
ClassDemo.props: Changes are in functions only. Possibly avoidable re-render?
Functions before: {e: ƒ}
Functions after: {e: ƒ}
```

After fixing prop `e` so the functions are the same, the next error is uncovered:

```
ClassDemo.props: Value did not change. Avoidable re-render!
Before: {a: 1, b: {…}, e: 1, f: 1}
After: {a: 1, b: {…}, e: 1, f: 1}
"b" property is not equal by reference
```

After fixing prop `b` so the objects are the same, the next (final) error is uncovered:

```
ClassDemo.props: Value did not change. Avoidable re-render!
Before: {a: 1, b: 1, e: 1, f: 1}
After: {a: 1, b: 1, e: 1, f: 1}
```

After making the component a `PureComponent`, finally we have fixed all the errors.

Ideally, we would aggregate all reasons into one log. E.g.

```
ClassDemo.props:
- Functions for props `e` are not reference equal but are similar.
- Objects for props `b` are not reference equal but are deep equal.
- Props `a` and `f` are reference equal, but component is not `PureComponent`.
Possibly avoidable re-render?
```

**Comment by vzaidman** [comment]
try this:
https://github.com/welldone-software/why-did-you-render

**Comment by maicki** [comment]
Closing this Issue. For further details please look at: #63
