### ISSUE TITLE
Regexp include issue

### ISSUE THREAD

**Issue by imornar** [maicki/why-did-you-update#22]
How it possible to include only one component?
What I tried so far:
```
{
    include: /^FullComponentName/
}
```
This does not work. 
Also How to include more components?

Thanks

**Comment by maicki** [comment]
@imornar Hey - It's just a regular regex against the name of the component. What is an example of a component name you would like to include and what regex do you use?

**Comment by imornar** [comment]
For example I have component named `UserList`, I tried `/^UserList/` and nothing is tracked in console. After I remove all includes and excludes rules,  `UserList` is properly tracked in console (along with many many other components which I would love to filter out)

**Comment by maicki** [comment]
`include` should be a list:
{
    include: [/^FullComponentName/]
}

This is also the way you can more components.

**Comment by maicki** [comment]
I will close this issue as it seems this is resolved. Please reopen otherwise. Thanks!
