### ISSUE TITLE
Module not found:  Can't resolve 'why-did-you-update'

### ISSUE THREAD

**Issue by danilosilvadev** [maicki/why-did-you-update#24]
I installed this package but is showing this message when I try to use it.

I noticed that inside node modules there isn't any 'why-did-you-update' package but in my package.json there is installed "why-did-you-update": "^0.1.1". Can someone help me?

**Comment by adrianotadao** [comment]
Hey man, strange but I will send my example here. I just added this lib to my project and it works.

This is my index.js, where I render the application on the root div.
 
```javascript
import { whyDidYouUpdate } from 'why-did-you-update'

if (process.env.NODE_ENV !== 'production') {
  whyDidYouUpdate(React)
}

const store = configureStore(rootReducer)

ReactDOM.render((
  <Provider store={ store }>
    <Routes />
  </Provider>
), document.getElementById('root'))
```

If you have this in your package.json, there is no sense to raise an error..

**Comment by maicki** [comment]
@danilosilvadev Do you see still have this problem? Do you see this issue in production or development? If you only want to have it in development add it to your `devDependencies` in your package.json and wrap it in something like @adrianotadao did:

```
export const enableWhyDidYouUpdate = () => {
  if (process.env.NODE_ENV !== 'production') {
    // eslint-disable-next-line global-require
    const { whyDidYouUpdate } = require('why-did-you-update');
    whyDidYouUpdate(React);
  }
};
```

**Comment by joshyhargreaves** [comment]
@danilosilvadev there is absolutely no way that you can use this package via npm if it does not exist in your `node_modules` folder. Did you run `yarn/npm install`?

**Comment by danilosilvadev** [comment]
Hi everybody. i'm not using why did you update in this project. @joshyhargreaves i did npm install several times. Anyway thank's for your attention.
