### ISSUE TITLE
Where to monkeypatch?

### ISSUE THREAD

**Issue by joetidee** [maicki/why-did-you-update#28]
In the readme, you have this:
```
import React from 'react';

if (process.env.NODE_ENV !== 'production') {
  const {whyDidYouUpdate} = require('why-did-you-update');
  whyDidYouUpdate(React);
}
```
but you don't provide any context as to where this is being done - in each file that uses React, when you start the dev server, etc..

**Comment by rodrigobdz** [comment]
@joetidee  You only need to initialize it in one file. I did it in my App.js which looks like this:

```js
// @flow

import React from 'react'
import { Provider } from 'react-redux'

import { PersistGate } from 'redux-persist/integration/react'
import AppNavigator from 'components/shared/AppNavigator'
import { store, persistor } from 'redux-setup'

if (process.env.NODE_ENV === 'development') {
  const { whyDidYouUpdate } = require('why-did-you-update')
  whyDidYouUpdate(React)
}

const App = () => (
  <Provider store={store}>
    <PersistGate loading={null} persistor={persistor}>
      <AppNavigator />
    </PersistGate>
  </Provider>
)

export default App
```

Hope it helps.

**Comment by maicki** [comment]
@joetidee As @rodrigobdz said, you only have do it once within the app. This could be in something like `App.js` or `index.js`.

I will close this issue, reopen if it is still not clear. I would also appreciate any PR to improve the documentation around this.
