### ISSUE TITLE
Why is this Component rerendered but nothing (props/state) changes

### ISSUE THREAD

**Issue by digitalkaoz** [maicki/why-did-you-update#29]
```
defaultNotifier.js:28 Map.props: Value did not change. Avoidable re-render!
defaultNotifier.js:28 Map.state: Value is the same (equal by reference). Avoidable re-render!
```

it has no custom `componentDidUpdate`, so what am i doing wrong here? (its wrapped in https://github.com/faceyspacey/react-universal-component).

i can provide the component and everything if needed...

**Comment by Jbrownstone** [comment]
By default the React.Component componentDidUpdate function returns true everytime.

If you extends your component from React.Component try extending it from PureComponent intstead, wich implement a compare during the componentDidUpdate methode.

**Comment by alp82** [comment]
Yes please provide the components and code involved.

**Comment by vzaidman** [comment]
this is 2 months old so I'm closing it.
you are welcome to provide us with a demo and reopen the ticket.
