### ISSUE TITLE
createClass deprecation notice

### ISSUE THREAD

**Issue by Schlesiger** [maicki/why-did-you-update#3]
I get the following warning when using `why-did-you-update`:

```
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
```

Also, any chance this fork will be published to NPM now that the offer is no longer continuing?

**Comment by maicki** [comment]
@Schlesiger Hey! How did you declare `why-did-you-update` in your `package.json`?

**Comment by Schlesiger** [comment]
@maicki , I just updated to the latest release. `why-did-you-update` is in `package.json` like so:
```json
{
  "devDependencies": {
    "why-did-you-update": "^0.1.0"
  }
}
```

**Comment by maicki** [comment]
@Schlesiger And you still get the error?

**Comment by Schlesiger** [comment]
@maicki Yup, same error. After a full clean and everything. It happens with both `require()` and `System.import()`.

**Comment by maicki** [comment]
@Schlesiger I just tested this out in a new project. This warning only appears if you have a component that is defined via `createClass` somewhere in your project. If there is no component defined this way it will not show up.

Why did you update supports React 14+ therefore I think there is no plan to remove the `createClass` hook for now.

**Comment by Schlesiger** [comment]
Yeah there must be some dependency which uses `createClass`. I would have expected the warning to appear without `why-did-you-update` but perhaps `babel` is doing some magic to transform it. I'm not sure what magic `why-did-you-update` is doing to make the `createClass` surface the error.

Thanks for looking into it. It's pretty easy to enable/disable `why-did-you-update` so it isn't always running during development, and I can just ignore the errors when it is.

**Comment by maicki** [comment]
What `why-did-you-update` is basically it hooks into `createClass` to add a Mixin that hooks into `componentDidUpdate` to determine the diff that based on that if a re-render occurred or not.
