### ISSUE TITLE
Performance hit with React 16.5.1

### ISSUE THREAD

**Issue by hitsthings** [maicki/why-did-you-update#30]
I'm not sure which version of React it started in, but now `props.children` has an `_owner` property which is a `FiberNode`. From there, you end up walking a giant tree of `FiberNode`s.

In `why-did-you-update`'s `classifyDiff`, it happily goes down the path of checking these FiberNode objects for equality (this is in `_.isEqual` from Lodash). We have a case where typing a character into a text field has a 2 second delay as it compares this giant tree.

You might need to switch to [`_.isEqualWith`](https://lodash.com/docs/4.17.10#isEqualWith) and add a customizer to call things equal if they are both `FiberNode`s (not sure if you need to actually ensure the FiberNodes _are_ equal or not, but I'm guessing not).

**Comment by vzaidman** [comment]
@hitsthings please verify now with the new version.

**Comment by hitsthings** [comment]
Thanks for looking at this. I'm probably not going to have time to verify the fix, so hopefully someone else who hits it can give it a go. Best of luck!

**Comment by TheHolyWaffle** [comment]
1.0.6 seems to have improved the performance at first sight, maybe even to what it was before 1.x

**Comment by vzaidman** [comment]
yes we only track what we need to track and we use a smart deep equality tester now. :D
