### ISSUE TITLE
How to fix "property is not equal by reference"

### ISSUE THREAD

**Issue by nalumachurakesh** [maicki/why-did-you-update#32]
Hi,

I'm getting "property is not equal by reference" warning in the console without any change in the data.
Please suggest me how to fix this. Thanks in advance.

**Comment by vzaidman** [comment]
Check out the readme again. I just improved it.
At the bottom you can find "Common fixing scenarios"
https://github.com/maicki/why-did-you-update#common-fixing-scenarios

Also I added a sandbox that you can play with. (notice the console):
https://codesandbox.io/s/mywnl5xp58?expanddevtools=1

Reopen if you still don't understand.
