### ISSUE TITLE
1.0.x breaks react-hot-loader

### ISSUE THREAD

**Issue by lynkx** [maicki/why-did-you-update#45]
After upgrade to WDYU 1.0.6, I've noticed that the HMR has stopped working. Although everything is up and running, it seems that WDYU is blocking the updates from 'hot' modules - meaning, no changes in the rendered view.

**Comment by zhukevgeniy** [comment]
+1

**Comment by zhukevgeniy** [comment]
I don’t know why but I’ve just updated all the dependencies and it seems to
work.

Thank you for your feedback:)

пт, 16 нояб. 2018 г. в 12:28, Vitali Zaidman <notifications@github.com>:

**Comment by lynkx** [comment]
Sorry for the late reply, was offline for a while.

@vzaidman seems like your sandbox is refreshing an entire page.
I've made a sandbox where the issue can be reproduced: https://codesandbox.io/s/rm5wvq792n

1. open the src/app.js
2. change the Hello world text
3. hit save (changes won't be updated in the rendered view)
4. open the src/index.js
5. comment out the WDYU call
6. repeat steps 1., 2., 3. (changes should now be visible in the rendered view immediately)

Can you take a look?
