### ISSUE TITLE
Cannot set property createClass of #<Object> which has only a getter

### ISSUE THREAD

**Issue by SilentImp** [maicki/why-did-you-update#5]
Keep getting this error.
```
import React from 'react';
const {whyDidYouUpdate} = require('why-did-you-update');
whyDidYouUpdate(React);
```
<img width="724" alt="screenshot 2017-11-03 14 43 14" src="https://user-images.githubusercontent.com/217308/32374270-94a005e4-c0a5-11e7-8784-7a685e3c026e.png">
<img width="596" alt="screenshot 2017-11-03 14 43 40" src="https://user-images.githubusercontent.com/217308/32374272-94c27354-c0a5-11e7-81f6-3d92cea661e1.png">

**Comment by SilentImp** [comment]
```
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-redux": "^5.0.5",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
```

**Comment by SilentImp** [comment]
It work with React 15.4.2.
In 15.6.2 or 16 — @why-did-you-update is dead cold.

**Comment by maicki** [comment]
@SilentImp Do you point to this repo in your `package.json`? I didn't release a version based off of master yet. It will happen soon though.

**Comment by SilentImp** [comment]
yay, no, i'll try it.

**Comment by maximgatilin** [comment]
@fliptheweb It helped me, thanks!

**Comment by maicki** [comment]
Awesome, it seems this issue is resolved. Btw version 0.1.0 was pushed to npm today so you should be good with changing the dependencies url back to npm:

```
"why-did-you-update": "^0.1.0"
```
