### ISSUE TITLE
Include or exlude path

### ISSUE THREAD

**Issue by davidpaulsson** [maicki/why-did-you-update#50]
Is it possible to exclude all modules imported from a certain path (such as node_modules) or include components from path?

I'm trying to use this with my react native app, but it's currently unusable due to all components coming from redux, react-navigation and other high impact libs (not all are as easy as redux to exclude in the regex). Also being react-native all primities are being treated as components so why-did-you-update throws logs for ActivityIndicator, YellowBox, View, Text, Touchable* etc causing memory crashes.

**Comment by vzaidman** [comment]
try this:
https://github.com/welldone-software/why-did-you-render
