### ISSUE TITLE
No support to "React.createFactory"

### ISSUE THREAD

**Issue by vzaidman** [maicki/why-did-you-update#51]
Looks like some libraries are using `React.createFactory` which in turn uses the native `React.createElement`. For example recompose:
https://github.com/acdlite/recompose/blob/master/src/packages/recompose/lifecycle.js

you can find an example in the following sandbox:
https://codesandbox.io/s/kmw33kjo97

I solved it here:
https://github.com/welldone-software/why-did-you-render/commit/43a08e62779d9f9988b85bfb840b383464ad8629

Here is the sandbox proving it:
https://codesandbox.io/s/65kvw1x4z

on the [@welldone-software/why-did-you-render](https://github.com/welldone-software/why-did-you-render) project. Everybody are welcome to copy this solution and open a PR on `why-did-you-update`.

**Comment by maicki** [comment]
Closing this Issue. For further details please look at: #63
