### ISSUE TITLE
Hooks are not supported

### ISSUE THREAD

**Issue by VincentLanglet** [maicki/why-did-you-update#52]
I use the last version of React with hooks in my code.

As soon as I added `why-did-you-update`.
```tsx
import React from 'react';
import ReactDOM from 'react-dom';

if (process.env.NODE_ENV !== 'production') {
  const { whyDidYouUpdate } = require('why-did-you-update');
  whyDidYouUpdate(React);
}

import App from './pages/App';

ReactDOM.render(<App />, document.getElementById('root'));
```

I receive the error
> Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

The code works fine without this library.

**Comment by vzaidman** [comment]
can you try https://github.com/welldone-software/why-did-you-render?

**Comment by VincentLanglet** [comment]
@vzaidman There is no error

**Comment by vzaidman** [comment]
ok. consider using it instead

**Comment by joelstransky** [comment]
> can you try https://github.com/welldone-software/why-did-you-render?

This worked for me.

**Comment by vzaidman** [comment]
https://github.com/welldone-software/why-did-you-render supports hook tracking as of version 3!

re-renders that are caused by hooks would be now caught and reported!

**Comment by mikeaustin** [comment]
Is this project deprecated in favor of why-did-you-render?

**Comment by 1eeing** [comment]
> can you try https://github.com/welldone-software/why-did-you-render?

When i use why-did-you-render instead, i got nothing.

**Comment by kriskate** [comment]
> > can you try https://github.com/welldone-software/why-did-you-render?
> 
> When i use why-did-you-render instead, i got nothing.

Try
```

if (process.env.NODE_ENV !== "production") {
  const whyDidYouRender = require("@welldone-software/why-did-you-render");

  whyDidYouRender(React, {
    collapseGroups: true,
    include: [/.*/],
    // exclude: [/^Link/, /^Route/, /^BrowserRouter/],
  });
}
```
