### ISSUE TITLE
Circular refs and react-fast-compare

### ISSUE THREAD

**Issue by Scritik** [maicki/why-did-you-update#55]
Hi,

`why-did-you-update` is using `react-fast-compare` to compare but `react-fast-compare` does not handle circular refs. Everything was working fine with older versions.

I understand that speed is really important but is it possible to have a choice between `react-fast-compare` and the old diff? Or at least an option to use a custom diff function? Because right now, I'm stuck with an old version.

> Warning: react-fast-compare does not handle circular references. RangeError Maximum call stack size exceeded

Thanks.

**Comment by vzaidman** [comment]
hey this is solved in "https://github.com/welldone-software/why-did-you-render"

**Comment by Scritik** [comment]
Thanks, but it's not working with Preact :/

**Comment by vzaidman** [comment]
and why-did-you-update does?

**Comment by Scritik** [comment]
yes!

**Comment by vzaidman** [comment]
you can make a PR that fixes it. ill approve it if tests are passing.

**Comment by maicki** [comment]
Closing this Issue. For further details please look at: #63
