### ISSUE TITLE
 General cleanup and dependencies update

### ISSUE THREAD

**Issue by maicki** [maicki/why-did-you-update#6]
After releasing 0.1.0 we should look into doing some cleanup:
- [x] Update dependencies
- [x] Update peerDependencies

**Comment by asaloff** [comment]
I'm receiving a: ```npm WARN why-did-you-update@0.1.0 requires a peer of react@^15.0 || 0.14.x but none was installed``` when I try to install with react@16.2.0

**Comment by maicki** [comment]
@asaloff Did you install via npm? The change to the `peerDependencies` is only on master yet and not published to npm. If you install it directly from master by e.g. declaring the package in your `package.json` as `whyDidYouUpdate: maicki/whyDidYouUpdate` do you still get the WARN?

**Comment by maicki** [comment]
Closing this issue for now as there is nothing to do yet.

**Comment by asaloff** [comment]
Thanks for the response. I added `"why-did-you-update": "maicki/why-did-you-update"` to `package.json` and the warning goes away. Thanks for the library.
