### ISSUE TITLE
React@16 support

### ISSUE THREAD

**Issue by jeron-diovis** [maicki/why-did-you-update#7]
Do you planning to add "^16" to react peer dependency?

**Comment by maicki** [comment]
Yes. Related Issue: #6

**Comment by maicki** [comment]
I just pushed an update to master that updates the peerDependencies to include React 16.

**Comment by klimashkin** [comment]
What npm module name is this?

**Comment by maicki** [comment]
@klimashkin The update to React@16 is not on nom yet. The npm name is just `why-did-you-update`

**Comment by jeron-diovis** [comment]
> The update to React@16 is not on npm yet. The npm name is just `why-did-you-update`

@maicki `why-did-you-update` in npm points to abandoned https://github.com/garbles/why-did-you-update. How do I install this, maintained version?

**Comment by maicki** [comment]
@jeron-diovis I have to push a new version to npm that will install the version in here. For the time being you can install it via:

```
"why-did-you-update": "maicki/why-did-you-update"
```
